/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Civic Vitality — Material 3 inspired palette ──────────────────
        'surface':                    'var(--color-surface)',
        'surface-dim':                'var(--color-surface-dim)',
        'surface-bright':             'var(--color-surface-bright)',
        'surface-container-lowest':   'var(--color-surface-container-lowest)',
        'surface-container-low':      'var(--color-surface-container-low)',
        'surface-container':          'var(--color-surface-container)',
        'surface-container-high':     'var(--color-surface-container-high)',
        'surface-container-highest':  'var(--color-surface-container-highest)',
        'on-surface':                 'var(--color-on-surface)',
        'on-surface-variant':         'var(--color-on-surface-variant)',
        'inverse-surface':            'var(--color-inverse-surface)',
        'inverse-on-surface':         'var(--color-inverse-on-surface)',
        'outline':                    'var(--color-outline)',
        'outline-variant':            'var(--color-outline-variant)',
        'surface-tint':               'var(--color-surface-tint)',
        'primary':                    'var(--color-primary)',
        'on-primary':                 'var(--color-on-primary)',
        'primary-container':          'var(--color-primary-container)',
        'on-primary-container':       'var(--color-on-primary-container)',
        'inverse-primary':            'var(--color-inverse-primary)',
        'secondary':                  'var(--color-secondary)',
        'on-secondary':               'var(--color-on-secondary)',
        'secondary-container':        'var(--color-secondary-container)',
        'on-secondary-container':     'var(--color-on-secondary-container)',
        'tertiary':                   'var(--color-tertiary)',
        'on-tertiary':                'var(--color-on-tertiary)',
        'tertiary-container':         'var(--color-tertiary-container)',
        'on-tertiary-container':      'var(--color-on-tertiary-container)',
        'error':                      'var(--color-error)',
        'on-error':                   'var(--color-on-error)',
        'error-container':            'var(--color-error-container)',
        'on-error-container':         'var(--color-on-error-container)',
        'primary-fixed':              'var(--color-primary-fixed)',
        'primary-fixed-dim':          'var(--color-on-primary-container)',
        'on-primary-fixed':           'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant':   'var(--color-on-primary-fixed-variant)',
        'secondary-fixed':            'var(--color-secondary-fixed)',
        'secondary-fixed-dim':        'var(--color-secondary-fixed-dim)',
        'on-secondary-fixed':         'var(--color-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'background-cv':              'var(--color-background-cv)',
        'on-background':              'var(--color-on-background)',
        'surface-variant':            'var(--color-surface-variant)',
        // ── Legacy CSS-var aliases (keep for remaining old references) ────
        moss:           'var(--moss)',
        'moss-light':   'var(--moss-light)',
        terracotta:     'var(--terracotta)',
        'amber-dim':    'var(--amber-dim)',
        'olive-grey':   'var(--olive-grey)',
        ink:            'var(--ink)',
        'bg-base':      'var(--bg-base)',
        'bg-panel':     'var(--bg-panel)',
        'bg-inset':     'var(--bg-inset)',
        'bg-hover':     'var(--bg-hover)',
        'text-primary':   'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted':     'var(--text-muted)',
        'border-hair':   'var(--border-hair)',
        'border-med':    'var(--border-med)',
        'border-strong': 'var(--border-strong)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        error:   'var(--error)',
        brand: {
          DEFAULT: 'var(--moss)',
          dark: 'var(--brand-dark)',
        },
      },
      fontFamily: {
        sans:    ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        mono:    ['JetBrains Mono', 'Courier New', 'monospace'],
        'body-sm':        ['"Plus Jakarta Sans"'],
        'label-sm':       ['"Plus Jakarta Sans"'],
        'label-md':       ['"Plus Jakarta Sans"'],
        'label-lg':       ['"Plus Jakarta Sans"'],
        'headline-sm':    ['"Plus Jakarta Sans"'],
        'headline-md':    ['"Plus Jakarta Sans"'],
        'headline-lg':    ['"Plus Jakarta Sans"'],
        'headline-xl':    ['"Plus Jakarta Sans"'],
        'body-md':        ['"Plus Jakarta Sans"'],
        'body-lg':        ['"Plus Jakarta Sans"'],
        'metric-display': ['"Plus Jakarta Sans"'],
      },
      fontSize: {
        'body-sm':        ['12px', { lineHeight: '18px', letterSpacing: '0.01em',   fontWeight: '400' }],
        'label-sm':       ['11px', { lineHeight: '14px', letterSpacing: '0.04em',   fontWeight: '700' }],
        'label-md':       ['12px', { lineHeight: '16px', letterSpacing: '0.02em',   fontWeight: '600' }],
        'label-lg':       ['14px', { lineHeight: '20px', letterSpacing: '0.01em',   fontWeight: '600' }],
        'body-md':        ['14px', { lineHeight: '22px', letterSpacing: '0em',      fontWeight: '400' }],
        'body-lg':        ['16px', { lineHeight: '26px', letterSpacing: '0em',      fontWeight: '400' }],
        'headline-sm':    ['16px', { lineHeight: '24px', letterSpacing: '0em',      fontWeight: '600' }],
        'headline-md':    ['20px', { lineHeight: '28px', letterSpacing: '-0.01em',  fontWeight: '600' }],
        'headline-lg':    ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-xl':    ['36px', { lineHeight: '44px', letterSpacing: '-0.02em',  fontWeight: '700' }],
        'metric-display': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em',  fontWeight: '700' }],
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs':  '0.5rem',
        'space-sm':  '0.75rem',
        'space-md':  '1rem',
        'space-lg':  '1.5rem',
        'space-xl':  '2rem',
        'space-2xl': '2.5rem',
        'space-3xl': '3rem',
        'space-4xl': '4rem',
        'gutter':    '1.5rem',
        'gutter-sm': '1rem',
        'margin':    '2rem',
        'margin-sm': '1rem',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.125rem',
        md:      '0.375rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      letterSpacing: {
        'tighter-display': '-0.03em',
        'tight-heading':   '-0.025em',
        'normal-ui':       '-0.01em',
        'wide-label':      '0.08em',
        'wider-caps':      '0.1em',
      },
    },
  },
  plugins: [],
}
