/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Civic Vitality — Material 3 inspired palette ──────────────────
        'surface':                    '#f6fbf5',
        'surface-dim':                '#d7dbd6',
        'surface-bright':             '#f6fbf5',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f0f5f0',
        'surface-container':          '#ebefea',
        'surface-container-high':     '#e5e9e4',
        'surface-container-highest':  '#dfe4df',
        'on-surface':                 '#181d1a',
        'on-surface-variant':         '#404942',
        'inverse-surface':            '#2c322e',
        'inverse-on-surface':         '#edf2ed',
        'outline':                    '#707971',
        'outline-variant':            '#bfc9bf',
        'surface-tint':               '#296a46',
        'primary':                    '#004527',
        'on-primary':                 '#ffffff',
        'primary-container':          '#1b5e3b',
        'on-primary-container':       '#92d5a9',
        'inverse-primary':            '#92d5a9',
        'secondary':                  '#a23e18',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#fe8357',
        'on-secondary-container':     '#6f2000',
        'tertiary':                   '#353e38',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#4c554e',
        'on-tertiary-container':      '#c0c9c0',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'primary-fixed':              '#aef2c4',
        'primary-fixed-dim':          '#92d5a9',
        'on-primary-fixed':           '#002110',
        'on-primary-fixed-variant':   '#085230',
        'secondary-fixed':            '#ffdbcf',
        'secondary-fixed-dim':        '#ffb59c',
        'on-secondary-fixed':         '#390c00',
        'on-secondary-fixed-variant': '#822801',
        'background-cv':              '#f6fbf5',
        'on-background':              '#181d1a',
        'surface-variant':            '#dfe4df',
        // ── Legacy CSS-var aliases (keep for remaining old references) ────
        moss:           'var(--moss)',
        'moss-light':   'var(--moss-light)',
        terracotta:     'var(--terracotta)',
        'amber-dim':    'var(--amber-dim)',
        'olive-grey':   'var(--olive-grey)',
        ink:            'var(--ink)',
        'bg-base':      'var(--bg-base)',
        'bg-panel':     'var(--bg-panel)',
        'bg-inset':     'var(--bg-inset)',
        'bg-hover':     'var(--bg-hover)',
        'text-primary':   'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted':     'var(--text-muted)',
        'border-hair':   'var(--border-hair)',
        'border-med':    'var(--border-med)',
        'border-strong': 'var(--border-strong)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        error:   'var(--error)',
        brand: {
          DEFAULT: 'var(--moss)',
          dark: 'var(--brand-dark)',
        },
      },
      fontFamily: {
        sans:    ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        mono:    ['JetBrains Mono', 'Courier New', 'monospace'],
        'body-sm':        ['"Plus Jakarta Sans"'],
        'label-sm':       ['"Plus Jakarta Sans"'],
        'label-md':       ['"Plus Jakarta Sans"'],
        'label-lg':       ['"Plus Jakarta Sans"'],
        'headline-sm':    ['"Plus Jakarta Sans"'],
        'headline-md':    ['"Plus Jakarta Sans"'],
        'headline-lg':    ['"Plus Jakarta Sans"'],
        'headline-xl':    ['"Plus Jakarta Sans"'],
        'body-md':        ['"Plus Jakarta Sans"'],
        'body-lg':        ['"Plus Jakarta Sans"'],
        'metric-display': ['"Plus Jakarta Sans"'],
      },
      fontSize: {
        'body-sm':        ['12px', { lineHeight: '18px', letterSpacing: '0.01em',   fontWeight: '400' }],
        'label-sm':       ['11px', { lineHeight: '14px', letterSpacing: '0.04em',   fontWeight: '700' }],
        'label-md':       ['12px', { lineHeight: '16px', letterSpacing: '0.02em',   fontWeight: '600' }],
        'label-lg':       ['14px', { lineHeight: '20px', letterSpacing: '0.01em',   fontWeight: '600' }],
        'body-md':        ['14px', { lineHeight: '22px', letterSpacing: '0em',      fontWeight: '400' }],
        'body-lg':        ['16px', { lineHeight: '26px', letterSpacing: '0em',      fontWeight: '400' }],
        'headline-sm':    ['16px', { lineHeight: '24px', letterSpacing: '0em',      fontWeight: '600' }],
        'headline-md':    ['20px', { lineHeight: '28px', letterSpacing: '-0.01em',  fontWeight: '600' }],
        'headline-lg':    ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-xl':    ['36px', { lineHeight: '44px', letterSpacing: '-0.02em',  fontWeight: '700' }],
        'metric-display': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em',  fontWeight: '700' }],
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs':  '0.5rem',
        'space-sm':  '0.75rem',
        'space-md':  '1rem',
        'space-lg':  '1.5rem',
        'space-xl':  '2rem',
        'space-2xl': '2.5rem',
        'space-3xl': '3rem',
        'space-4xl': '4rem',
        'gutter':    '1.5rem',
        'gutter-sm': '1rem',
        'margin':    '2rem',
        'margin-sm': '1rem',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.125rem',
        md:      '0.375rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      letterSpacing: {
        'tighter-display': '-0.03em',
        'tight-heading':   '-0.025em',
        'normal-ui':       '-0.01em',
        'wide-label':      '0.08em',
        'wider-caps':      '0.1em',
      },
    },
  },
  plugins: [],
}
